# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis_viewer2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1169, 948)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/OneDrive/workspace/emeter_analysis/eps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_12.addWidget(self.label_35)
        self.dir_select_edit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dir_select_edit.sizePolicy().hasHeightForWidth())
        self.dir_select_edit.setSizePolicy(sizePolicy)
        self.dir_select_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dir_select_edit.setObjectName("dir_select_edit")
        self.horizontalLayout_12.addWidget(self.dir_select_edit)
        self.dir_select_button = QtWidgets.QPushButton(Dialog)
        self.dir_select_button.setMinimumSize(QtCore.QSize(25, 0))
        self.dir_select_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.dir_select_button.setObjectName("dir_select_button")
        self.horizontalLayout_12.addWidget(self.dir_select_button)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.dataset_treeview = QtWidgets.QTreeView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataset_treeview.sizePolicy().hasHeightForWidth())
        self.dataset_treeview.setSizePolicy(sizePolicy)
        self.dataset_treeview.setObjectName("dataset_treeview")
        self.verticalLayout.addWidget(self.dataset_treeview)
        self.dataset_select_label = QtWidgets.QLabel(Dialog)
        self.dataset_select_label.setObjectName("dataset_select_label")
        self.verticalLayout.addWidget(self.dataset_select_label)
        self.file_listview = QtWidgets.QListView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.file_listview.sizePolicy().hasHeightForWidth())
        self.file_listview.setSizePolicy(sizePolicy)
        self.file_listview.setObjectName("file_listview")
        self.verticalLayout.addWidget(self.file_listview)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(Dialog)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.auto_bkg_radiobutton = QtWidgets.QRadioButton(self.widget_5)
        self.auto_bkg_radiobutton.setChecked(True)
        self.auto_bkg_radiobutton.setObjectName("auto_bkg_radiobutton")
        self.horizontalLayout_11.addWidget(self.auto_bkg_radiobutton)
        self.radioButton = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_11.addWidget(self.radioButton)
        self.gridLayout.addWidget(self.widget_5, 10, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 10, 0, 1, 1)
        self.roi_height_spinbox = QtWidgets.QSpinBox(Dialog)
        self.roi_height_spinbox.setMaximum(3000)
        self.roi_height_spinbox.setProperty("value", 700)
        self.roi_height_spinbox.setObjectName("roi_height_spinbox")
        self.gridLayout.addWidget(self.roi_height_spinbox, 2, 1, 1, 1)
        self.mask_spinbox = QtWidgets.QSpinBox(Dialog)
        self.mask_spinbox.setSingleStep(2)
        self.mask_spinbox.setProperty("value", 25)
        self.mask_spinbox.setObjectName("mask_spinbox")
        self.gridLayout.addWidget(self.mask_spinbox, 12, 1, 1, 1)
        self.beamenergy_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.beamenergy_spinbox.setMaximum(20.0)
        self.beamenergy_spinbox.setProperty("value", 3.3)
        self.beamenergy_spinbox.setObjectName("beamenergy_spinbox")
        self.gridLayout.addWidget(self.beamenergy_spinbox, 17, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 18, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 1)
        self.roi_top_spinbox = QtWidgets.QSpinBox(Dialog)
        self.roi_top_spinbox.setMaximum(3000)
        self.roi_top_spinbox.setProperty("value", 250)
        self.roi_top_spinbox.setObjectName("roi_top_spinbox")
        self.gridLayout.addWidget(self.roi_top_spinbox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.rotation_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.rotation_spinbox.setMinimum(-180.0)
        self.rotation_spinbox.setMaximum(180.0)
        self.rotation_spinbox.setSingleStep(0.5)
        self.rotation_spinbox.setProperty("value", 3.12)
        self.rotation_spinbox.setObjectName("rotation_spinbox")
        self.gridLayout.addWidget(self.rotation_spinbox, 8, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bkg_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.bkg_spinbox.setMaximumSize(QtCore.QSize(16777209, 16777215))
        self.bkg_spinbox.setDecimals(1)
        self.bkg_spinbox.setMaximum(65000.0)
        self.bkg_spinbox.setProperty("value", 256.0)
        self.bkg_spinbox.setObjectName("bkg_spinbox")
        self.horizontalLayout_4.addWidget(self.bkg_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_4, 11, 1, 1, 1)
        self.image_size_label = QtWidgets.QLabel(Dialog)
        self.image_size_label.setObjectName("image_size_label")
        self.gridLayout.addWidget(self.image_size_label, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sum_images_radiobutton = QtWidgets.QRadioButton(self.widget_4)
        self.sum_images_radiobutton.setChecked(True)
        self.sum_images_radiobutton.setObjectName("sum_images_radiobutton")
        self.horizontalLayout_10.addWidget(self.sum_images_radiobutton)
        self.each_image_radiobutton = QtWidgets.QRadioButton(self.widget_4)
        self.each_image_radiobutton.setObjectName("each_image_radiobutton")
        self.horizontalLayout_10.addWidget(self.each_image_radiobutton)
        self.gridLayout.addWidget(self.widget_4, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 21, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 16, 0, 1, 1)
        self.slit_screen_distance_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.slit_screen_distance_spinbox.setMaximum(200.0)
        self.slit_screen_distance_spinbox.setProperty("value", 23.0)
        self.slit_screen_distance_spinbox.setObjectName("slit_screen_distance_spinbox")
        self.gridLayout.addWidget(self.slit_screen_distance_spinbox, 16, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 15, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 17, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.pixelsize_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.pixelsize_spinbox.setSingleStep(1.0)
        self.pixelsize_spinbox.setProperty("value", 13.3)
        self.pixelsize_spinbox.setObjectName("pixelsize_spinbox")
        self.gridLayout.addWidget(self.pixelsize_spinbox, 15, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.medfilt_spinbox = QtWidgets.QSpinBox(Dialog)
        self.medfilt_spinbox.setMinimum(1)
        self.medfilt_spinbox.setMaximum(13)
        self.medfilt_spinbox.setProperty("value", 5)
        self.medfilt_spinbox.setObjectName("medfilt_spinbox")
        self.gridLayout.addWidget(self.medfilt_spinbox, 9, 1, 1, 1)
        self.roi_left_spinbox = QtWidgets.QSpinBox(Dialog)
        self.roi_left_spinbox.setMaximum(3000)
        self.roi_left_spinbox.setObjectName("roi_left_spinbox")
        self.gridLayout.addWidget(self.roi_left_spinbox, 3, 1, 1, 1)
        self.small_roi_spinbox = QtWidgets.QSpinBox(Dialog)
        self.small_roi_spinbox.setMaximum(9999)
        self.small_roi_spinbox.setProperty("value", 150)
        self.small_roi_spinbox.setObjectName("small_roi_spinbox")
        self.gridLayout.addWidget(self.small_roi_spinbox, 7, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.roi_width_spinbox = QtWidgets.QSpinBox(Dialog)
        self.roi_width_spinbox.setMaximum(3000)
        self.roi_width_spinbox.setProperty("value", 1400)
        self.roi_width_spinbox.setObjectName("roi_width_spinbox")
        self.gridLayout.addWidget(self.roi_width_spinbox, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 8, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.start_analysis_button = QtWidgets.QPushButton(Dialog)
        self.start_analysis_button.setObjectName("start_analysis_button")
        self.horizontalLayout_14.addWidget(self.start_analysis_button)
        self.cancel_pushbutton = QtWidgets.QPushButton(Dialog)
        self.cancel_pushbutton.setObjectName("cancel_pushbutton")
        self.horizontalLayout_14.addWidget(self.cancel_pushbutton)
        self.gridLayout.addLayout(self.horizontalLayout_14, 21, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_widget = ImageView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_widget.sizePolicy().hasHeightForWidth())
        self.image_widget.setSizePolicy(sizePolicy)
        self.image_widget.setObjectName("image_widget")
        self.verticalLayout_2.addWidget(self.image_widget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 6, 6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.file_radiobutton = QtWidgets.QRadioButton(self.widget_3)
        self.file_radiobutton.setChecked(True)
        self.file_radiobutton.setObjectName("file_radiobutton")
        self.horizontalLayout_9.addWidget(self.file_radiobutton)
        self.scan_radiobutton = QtWidgets.QRadioButton(self.widget_3)
        self.scan_radiobutton.setObjectName("scan_radiobutton")
        self.horizontalLayout_9.addWidget(self.scan_radiobutton)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.raw_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.raw_radiobutton.setObjectName("raw_radiobutton")
        self.horizontalLayout_8.addWidget(self.raw_radiobutton)
        self.processed_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.processed_radiobutton.setChecked(False)
        self.processed_radiobutton.setObjectName("processed_radiobutton")
        self.horizontalLayout_8.addWidget(self.processed_radiobutton)
        self.tight_radiobutton = QtWidgets.QRadioButton(self.widget)
        self.tight_radiobutton.setChecked(True)
        self.tight_radiobutton.setObjectName("tight_radiobutton")
        self.horizontalLayout_8.addWidget(self.tight_radiobutton)
        self.horizontalLayout_5.addWidget(self.widget)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.image_slider = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_slider.sizePolicy().hasHeightForWidth())
        self.image_slider.setSizePolicy(sizePolicy)
        self.image_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.image_slider.setObjectName("image_slider")
        self.horizontalLayout_5.addWidget(self.image_slider)
        self.image_ind_spinbox = QtWidgets.QSpinBox(Dialog)
        self.image_ind_spinbox.setMinimumSize(QtCore.QSize(50, 0))
        self.image_ind_spinbox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.image_ind_spinbox.setMaximum(999)
        self.image_ind_spinbox.setProperty("value", 0)
        self.image_ind_spinbox.setObjectName("image_ind_spinbox")
        self.horizontalLayout_5.addWidget(self.image_ind_spinbox)
        self.image_sel_pos_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_sel_pos_label.sizePolicy().hasHeightForWidth())
        self.image_sel_pos_label.setSizePolicy(sizePolicy)
        self.image_sel_pos_label.setMinimumSize(QtCore.QSize(40, 0))
        self.image_sel_pos_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.image_sel_pos_label.setObjectName("image_sel_pos_label")
        self.horizontalLayout_5.addWidget(self.image_sel_pos_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plot_widget = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setObjectName("plot_widget")
        self.horizontalLayout_3.addWidget(self.plot_widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 6, 6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.charge_radiobutton = QtWidgets.QRadioButton(self.widget_2)
        self.charge_radiobutton.setChecked(True)
        self.charge_radiobutton.setObjectName("charge_radiobutton")
        self.horizontalLayout_2.addWidget(self.charge_radiobutton)
        self.line_radiobutton = QtWidgets.QRadioButton(self.widget_2)
        self.line_radiobutton.setObjectName("line_radiobutton")
        self.horizontalLayout_2.addWidget(self.line_radiobutton)
        self.xp_radiobutton = QtWidgets.QRadioButton(self.widget_2)
        self.xp_radiobutton.setObjectName("xp_radiobutton")
        self.horizontalLayout_2.addWidget(self.xp_radiobutton)
        self.xp2_radiobutton = QtWidgets.QRadioButton(self.widget_2)
        self.xp2_radiobutton.setObjectName("xp2_radiobutton")
        self.horizontalLayout_2.addWidget(self.xp2_radiobutton)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(6, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 9, 0, 1, 1)
        self.bkg_label = QtWidgets.QLabel(Dialog)
        self.bkg_label.setMinimumSize(QtCore.QSize(50, 0))
        self.bkg_label.setObjectName("bkg_label")
        self.gridLayout_2.addWidget(self.bkg_label, 0, 1, 1, 1)
        self.moment_1_label = QtWidgets.QLabel(Dialog)
        self.moment_1_label.setObjectName("moment_1_label")
        self.gridLayout_2.addWidget(self.moment_1_label, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 13, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        self.moment_2_label = QtWidgets.QLabel(Dialog)
        self.moment_2_label.setObjectName("moment_2_label")
        self.gridLayout_2.addWidget(self.moment_2_label, 2, 1, 1, 1)
        self.xp2_e_label = QtWidgets.QLabel(Dialog)
        self.xp2_e_label.setObjectName("xp2_e_label")
        self.gridLayout_2.addWidget(self.xp2_e_label, 10, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.analysis_progressbar = QtWidgets.QProgressBar(Dialog)
        self.analysis_progressbar.setProperty("value", 0)
        self.analysis_progressbar.setObjectName("analysis_progressbar")
        self.gridLayout_2.addWidget(self.analysis_progressbar, 7, 0, 1, 2)
        self.eps_n_label = QtWidgets.QLabel(Dialog)
        self.eps_n_label.setObjectName("eps_n_label")
        self.gridLayout_2.addWidget(self.eps_n_label, 14, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 11, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 0, 1, 1)
        self.sigma_x_label = QtWidgets.QLabel(Dialog)
        self.sigma_x_label.setObjectName("sigma_x_label")
        self.gridLayout_2.addWidget(self.sigma_x_label, 8, 1, 1, 1)
        self.eps_label = QtWidgets.QLabel(Dialog)
        self.eps_label.setObjectName("eps_label")
        self.gridLayout_2.addWidget(self.eps_label, 13, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.xxp_e_label = QtWidgets.QLabel(Dialog)
        self.xxp_e_label.setObjectName("xxp_e_label")
        self.gridLayout_2.addWidget(self.xxp_e_label, 11, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 12, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 14, 0, 1, 1)
        self.x2_e_label = QtWidgets.QLabel(Dialog)
        self.x2_e_label.setObjectName("x2_e_label")
        self.gridLayout_2.addWidget(self.x2_e_label, 9, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 10, 0, 1, 1)
        self.charge_label = QtWidgets.QLabel(Dialog)
        self.charge_label.setObjectName("charge_label")
        self.gridLayout_2.addWidget(self.charge_label, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.rejected_images_label = QtWidgets.QLabel(Dialog)
        self.rejected_images_label.setObjectName("rejected_images_label")
        self.gridLayout_2.addWidget(self.rejected_images_label, 5, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Emittance meter scan analysis"))
        self.label_16.setText(_translate("Dialog", "Dataset:"))
        self.label_35.setText(_translate("Dialog", "Path"))
        self.dir_select_edit.setText(_translate("Dialog", "./data"))
        self.dir_select_button.setText(_translate("Dialog", "..."))
        self.dataset_select_label.setText(_translate("Dialog", "Dataset: -- positions x -- images"))
        self.auto_bkg_radiobutton.setText(_translate("Dialog", "Auto"))
        self.radioButton.setText(_translate("Dialog", "Manual"))
        self.label_33.setText(_translate("Dialog", "Bkg cut method"))
        self.label_4.setText(_translate("Dialog", "ROI left"))
        self.label_14.setText(_translate("Dialog", "Mask kernel"))
        self.image_size_label.setText(_translate("Dialog", "-- x --"))
        self.label_8.setText(_translate("Dialog", "Image size"))
        self.sum_images_radiobutton.setText(_translate("Dialog", "Sum"))
        self.each_image_radiobutton.setText(_translate("Dialog", "Each"))
        self.label_5.setText(_translate("Dialog", "ROI width"))
        self.label_26.setText(_translate("Dialog", "Analyze scan"))
        self.label_2.setText(_translate("Dialog", "ROI top"))
        self.label_22.setText(_translate("Dialog", "Slit - screen distance / cm"))
        self.label_21.setText(_translate("Dialog", "Pixel size / um"))
        self.label_23.setText(_translate("Dialog", "Beam energy / MeV"))
        self.label_34.setText(_translate("Dialog", "Small ROI width"))
        self.label_3.setText(_translate("Dialog", "ROI height"))
        self.label_32.setText(_translate("Dialog", "Images at pos handling"))
        self.label.setText(_translate("Dialog", "Med filt kernel"))
        self.label_10.setText(_translate("Dialog", "Bkg cut manual level"))
        self.label_18.setText(_translate("Dialog", "Rotation / deg"))
        self.start_analysis_button.setText(_translate("Dialog", "Start"))
        self.cancel_pushbutton.setText(_translate("Dialog", "Cancel"))
        self.label_9.setText(_translate("Dialog", "Show"))
        self.file_radiobutton.setText(_translate("Dialog", "File"))
        self.scan_radiobutton.setText(_translate("Dialog", "Scan proc"))
        self.raw_radiobutton.setText(_translate("Dialog", "Raw"))
        self.processed_radiobutton.setText(_translate("Dialog", "Proc"))
        self.tight_radiobutton.setText(_translate("Dialog", "Tight"))
        self.image_sel_pos_label.setText(_translate("Dialog", "-.-- mm"))
        self.label_20.setText(_translate("Dialog", "Plot"))
        self.charge_radiobutton.setText(_translate("Dialog", "Charge"))
        self.line_radiobutton.setText(_translate("Dialog", "Image line"))
        self.xp_radiobutton.setText(_translate("Dialog", "x\'"))
        self.xp2_radiobutton.setText(_translate("Dialog", "x\'²"))
        self.label_27.setText(_translate("Dialog", "<x²>"))
        self.bkg_label.setText(_translate("Dialog", "-.-"))
        self.moment_1_label.setText(_translate("Dialog", "-.--"))
        self.label_24.setText(_translate("Dialog", "Emittance"))
        self.moment_2_label.setText(_translate("Dialog", "-.--"))
        self.xp2_e_label.setText(_translate("Dialog", "-.--"))
        self.label_7.setText(_translate("Dialog", "xp^2"))
        self.eps_n_label.setText(_translate("Dialog", "-.--"))
        self.label_31.setText(_translate("Dialog", "<xx\'>"))
        self.sigma_x_label.setText(_translate("Dialog", "-.--"))
        self.eps_label.setText(_translate("Dialog", "-.--"))
        self.label_6.setText(_translate("Dialog", "xp"))
        self.xxp_e_label.setText(_translate("Dialog", "-.--"))
        self.label_19.setText(_translate("Dialog", "σₓ / mm"))
        self.label_28.setText(_translate("Dialog", "Normalized emittance"))
        self.x2_e_label.setText(_translate("Dialog", "-.--"))
        self.label_30.setText(_translate("Dialog", "<x\'²>"))
        self.charge_label.setText(_translate("Dialog", "---"))
        self.label_15.setText(_translate("Dialog", "Charge"))
        self.rejected_images_label.setText(_translate("Dialog", "-"))
        self.label_25.setText(_translate("Dialog", "Rejected"))
        self.label_11.setText(_translate("Dialog", "Bkg level"))
from pyqtgraph import ImageView, PlotWidget
